### ISSUE TITLE
Single quote gets escaped by chrome

### ISSUE THREAD

**Issue by gbishop** [Sage/jsurl#6]
I'm trying to use jsurl but the single quotes are getting converted to %27 by chrome and then parsing breaks... Maybe I don't understand how I'm supposed to use it? Do I need to URIEncode after JSURL.stringfy? And decode before JSURL.parse?

**Comment by akleiber** [comment]
I am having the same problem

**Comment by bjouhier** [comment]
`encodeURIComponent` is the recommended function to encode URL parameters and this function does **not** encode single quotes. But some browsers do encode them to protect against HTML injection (see first answer to http://stackoverflow.com/questions/75980/when-are-you-supposed-to-use-escape-instead-of-encodeuri-encodeuricomponent and https://bugs.chromium.org/p/chromium/issues/detail?id=292740). This was not the case when I designed JSURL (2011) and it came as a bad surprise.

The problem can be solved by replacing `%27` by `'` before passing strings to `JSURL.parse`. There is no need to do any replacement in the other direction (`JSURL.stringify`)  because `'` can be passed unescaped.

I'm going to fix the problem in JSURL itself having `JSURL.parse` do the replacement.

**Comment by bjouhier** [comment]
@akleiber  I just published 0.1.3 to NPM, with the fix.

@gbishop I missed the issue when you posted it. Sorry for that.

**Comment by akleiber** [comment]
Wow. That was fast. Thank you very much!


Am 16.04.2016 um 00:17 schrieb Bruno Jouhier <notifications@github.com<mailto:notifications@github.com>>:


@akleiber<https://github.com/akleiber> I just published 0.1.3 to NPM, with the fix.

@gbishop<https://github.com/gbishop> I missed the issue when you posted it. Sorry for that.

-
